name: magic_lang
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - pip:
    - paddlepaddle==2.4.2
    - paddleocr==2.6.1.3
    - pynput==1.7.6
    - tk==0.1.0
    - pyttsx3==2.90
    - customtkinter==5.1.2